gatewayClasses:
  - name: cluster-gateway
    controllerName: example.net/gateway-controller
  - name: regional-gateway
    controllerName: example.net/region-gateway-controller
  - name: private-gateway
    controllerName: example.net/private-controller

gateways:
  - name: eg
    gatewayClassName: eg
    listeners:
      - name: http
        protocol: HTTP
        port: 80
